apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: real-devops-challenge-app
  name: real-devops-challenge-app-controller
spec:
  replicas: 2
  selector:
    name: real-devops-challenge-app
  template:
    metadata:
      labels:
        name: real-devops-challenge-app
    spec:
      containers:
        - image: angulito/the-real-challenge-devops:latest
          name: real-devops-challenge-app
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: http-server
          env:
          - name: MONGO_URI
            value: mongodb://mongo:27017/the-real-devops-challenge