version: 2
jobs:

  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          FLASK_CONFIG: testing

    working_directory: ~/the-real-devops-challenge

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - setup_remote_docker:
          version: 18.05.0-ce

      - run:
          name: Set docker image tag
          command: |
            SHORT_COMMIT_HASH="$(git rev-parse --short=8 HEAD)"
            if [ $CIRCLE_BRANCH == 'master' ]; then
                BRANCH_TAG_PREFIX='master'
            else
                BRANCH_TAG_PREFIX='branch'
            fi
            echo "export IMAGE_NAME=the-real-devops-challenge" >> $BASH_ENV
            echo "export IMAGE_TAG=${BRANCH_TAG_PREFIX}-${SHORT_COMMIT_HASH}" >> $BASH_ENV

      - run:
          name: Build docker image
          command: |
            docker build -t angulito/$IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: Push docker image
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push angulito/$IMAGE_NAME:$TAG

  deploy:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - run:
          name: Deploy app to the cloud provider via Docker
          command: |
            echo "TODO"

  test:
    docker:
      - image: painless/tox

    working_directory: /tmp/app

    steps:
      - checkout

      - run:
          name: Running tests
          command: tox


workflows:
  version: 2

  build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master