apiVersion: v1
kind: Service
metadata:
  name: real-devops-challenge-app
  labels:
    name: real-devops-challenge-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: real-devops-challenge-app